[package]
name = "webx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adw = { version = "0.6.0", package = "libadwaita", features = ["v1_5"] }
async-channel = "2.2.1"
gtk = { version = "0.8.1", package = "gtk4", features = ["v4_14"] }
reqwest = "0.12.3"
tokio = { version = "1", features = ["rt-multi-thread"] }
